version: '3.8'

services:
  app:
    build: .
    container_name: fastapi-yolo
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      ollama:
        condition: service_healthy
    environment:
      - OLLAMA_URL=http://ollama:11434
    restart: always

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama  # Persistencia del modelo
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        ollama pull gemma3:4b
        ollama serve
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:11434/api/generate"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: always

volumes:
  ollama_data:
