version: "3.8"

services:
  fastapi:
    build: .
    container_name: DetectPlacaOCR
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      - ollama
    restart: always

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_models:/root/.ollama
    restart: always
    entrypoint: ["/bin/sh", "-c", "ollama pull gemma3:4b && ollama serve"]

volumes:
  ollama_models:
